<h2>Numpy Library :-</h2>

Numpy is a fundamental library for scientific computing in Python, widely used for its powerful features and capabilities. 

Numpy provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

Numpy allows to perform arithmetic operations on arrays of different shapes and sizes without needing to explicitly reshape them. 
This makes code simpler and more intuitive.

Many other scientific computing and data analysis libraries, such as SciPy, Pandas, Matplotlib, and Scikit-Learn, are built on top of NumPy arrays, 
ensuring compatibility and seamless integration.

Numpy arrays consume less memory.

Numpy includes functions for linear algebra operations, Fourier transforms, and random number generation, which are essential for many scientific and engineering applications.

In [1]:
# To Download numpy library => pip install numpy 
# Import the numpy library as np

import numpy as np

<h4>1-Dimension Array :-</h4>

In [3]:
# Creation of array 1D
arr = np.array([34,54,65,12,76,89])
arr

array([34, 54, 65, 12, 76, 89])

In [47]:
type(arr) # ndarray => n dimensional array

# type() - This function is used to determine the type of an object.

numpy.ndarray

In [48]:
arr.dtype
# The dtype attribute of a Numpy array is used to determine the type of elements stored in the array.

dtype('int64')

In [49]:
arr.size #  The size attribute of an array returns the total number of elements in the array

6

In [50]:
len(arr) # The len() function is a built-in Python function used to get the number of items in a container

6

In [51]:
arr.ndim # The ndim attribute is used to determine the number of dimensions of an array. 

1

<h5>Indexing in 1-D Array:-</h5>

Indexing in a 1D Numpy array is similar to indexing in standard Python lists. 

In [13]:
# Creating a 1D NumPy array
arr = np.array([100,200,300,400,500])

# Accessing elements
print(arr[0])  # Output: 1
print(arr[2])  # Output: 3

100
300


In [14]:
# updating elements
arr[1] = 10
print(arr)  # Output: [1,10,3,4,5,6]

[100  10 300 400 500]


In [15]:
# Accessing elements with starting and stopping index
print(arr[1:4])  # Output: [ 10 300 400]
print(arr[:3])   # Output: [100  10 300]
print(arr[::2])  # Output: [100 300 500]
print(arr[-3:])  # Output: [300 400 500]  (accessing with negative index)

[ 10 300 400]
[100  10 300]
[100 300 500]
[300 400 500]


In [17]:
# The numpy.random.randint() function in Numpy is used to generate random integers within a specified range.
arr = np.random.randint(1,100,200)
print(arr)

[78 59 70 89 96 99 98 24 74 33 60 31 68 61 49 69 49 91 46 20 70 15 51 13
 45  4 50 28 75  8 76 80 84 30 96 82  3 76 41 46 79 49 29 36 50 22 11 79
 30 98 55 69 97 38 25 63 97 24 26 94 30 20 78  2 16 97 95 25 54 34 21 18
 96 92 54 99 88  5  9 78 94 72 32 22 95 52 59 52 50 38 55 72 76 96 34 83
 93 60 78 90 40  6 54 97 13 35  9 99 97 88 17 29  4 51 16 74 78 10 68 16
 88 22 78 63 75 67 36 10 13 17 47 60 32 81 17 48 14 40 78 74 28 75 80 97
 68 47 63 25 85 24 42 78 93 22 10 29 76  8 60 16 50 94 12 84 83 96 91 88
 76 77 75 56 10 53 67 61 85 51 22  7 44 23 65 64 12 18 16 56 19 34  3 27
 20 25 96 77 23 31 27 48]


<h4>2-Dimension Array :-</h4>

2D arrays (also known as matrices) in NumPy is a common task in scientific computing and data analysis. 

NumPy provides a range of functionalities to create, manipulate, and perform operations on 2D arrays.

In [3]:
# Creating a 2D NumPy array
arr2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr2d)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [4]:
# Accessing elements
print("Element at (0, 2):", arr2d[0, 2])  # Output: 30
print("Element at (2, 0):", arr2d[2, 0])  # Output: 70

Element at (0, 2): 30
Element at (2, 0): 70


In [5]:
# updating elements
arr2d[1, 2] = 10
print("updating 2D Array:")
print(arr2d)

updating 2D Array:
[[10 20 30]
 [40 50 10]
 [70 80 90]]


In [6]:
# Accessing rows
print("First two rows:")
print(arr2d[:2])

First two rows:
[[10 20 30]
 [40 50 10]]


In [7]:
# Accessing columns
print("First two columns:")
print(arr2d[:, :2])

First two columns:
[[10 20]
 [40 50]
 [70 80]]


In [8]:
# Transposing the array
print("Transposed Array:")
print(arr2d.T)

Transposed Array:
[[10 40 70]
 [20 50 80]
 [30 10 90]]


In [9]:
# Summing all elements
print("Sum of all elements:", np.sum(arr2d))

Sum of all elements: 400


In [10]:
# Element-wise operations
print("Element-wise multiplication:")
print(arr2d * 2)

Element-wise multiplication:
[[ 20  40  60]
 [ 80 100  20]
 [140 160 180]]


In [11]:
# Matrix multiplication
arr2d_2 = np.array([[1, 2], [3, 4], [5, 6]])
print(np.dot(arr2d, arr2d_2))

[[ 220  280]
 [ 240  340]
 [ 760 1000]]


<h4>3-Dimension Array :-</h4>

3-dimensional (3D) arrays in Numpy involves similar concepts to working with 2D arrays but adds an additional dimension for more complex data structures.

In [16]:
arr3 = np.random.randint(1,100,(3,4,3))

In [17]:
# The shape attribute of an array provides a tuple representing the dimensions of the array.

arr3.shape # (table, row, column)

(3, 4, 3)

In [19]:
# Creating a 3D Numpy array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                  [[7, 8, 9], [10, 11, 12]], 
                  [[13, 14, 15], [16, 17, 18]]])

# Accessing specific elements
print(arr3d[0, 0, 0])  # Output: 1
print(arr3d[1, 1, 2])  # Output: 12
print(arr3d[2, 1, 1])  # Output: 17
arr3d

1
12
17


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

<h3>Numpy Functions :-</h3>

In [68]:
# The zeros() function in Numpy is used to create an array filled with zeros.

arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
arr = np.zeros((5,4)) # 10 row 5 column with item = 0
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
# The ones() function in Numpy is used to create an array filled with ones.

arr = np.ones((5,4)) # 10 row 5 column with item = 1
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [71]:
# The arange() function in Numpy is used to create arrays with evenly spaced values within a specified range.
# numpy.arange(start, stop, step)

np.arange(10) # creates array from range 0-10
# creates always 1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr = np.arange(100)
arr # 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
# The reshape() function in Numpy is used to change the shape of an existing array without modifying its data.
arr = arr.reshape(10,10) # 1D --> 2D
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
arr = np.array([10,20,50,40])
np.max(arr) # used to find the maximum value in an array.

np.int64(50)

In [34]:
np.min(arr) # used to find the minimum value in an array.

np.int64(10)

In [35]:
np.sum(arr) # used to compute the sum of array elements over a specified axis or the entire array.

np.int64(120)

In [36]:
np.argmin(arr) # returns the index position of the minimum item

np.int64(0)

In [37]:
np.argmax(arr) # returns the index position of the maximum item

np.int64(2)

In [38]:
# used to sort elements of an array along a specified axis. It returns a sorted copy of the array.
arr.sort() # Ascending order
arr

array([10, 20, 40, 50])

In [39]:
arr[::-1] # Descending order

array([50, 40, 20, 10])